### ISSUE TITLE
弹幕显示异常

### ISSUE THREAD

**Issue by aidistan** [aidistan/firefox-weixin-danmu#1]
最后一个字符有时候会换行，影响效果。

该bug出现不稳定，有待观察。

**Comment by aidistan** [comment]
与显示弹幕页面的全局样式有关，可以考虑为每个弹幕进行适度的样式重置。

**Comment by aidistan** [comment]
Fixed by 4b051aeeffdd7783f44ab9794b6e0180280a126e.

**Comment by tiansh** [comment]
建议可以试试样式里面加

``` css
* { all: unset !important; }
```

来解决样式的问题。
